version: 0.2

env:
  secrets-manager:
    AWS_ACCESS_KEY_ID: "github/Lambda-ECR/AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "github/Lambda-ECR/AWS_SECRET_ACCESS_KEY"
    AWS_REGION: "github/Lambda-ECR/AWS_REGION"
    ECR_REPOSITORY_URI: "github/Lambda-ECR/ECR_REPOSITORY_URI"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $ECR_REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"container-name","imageUri":"%s"}]' $ECR_REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
