version: 0.2

env:
  secrets-manager:
    DOCKER_HUB_CREDENTIALS: docker-hub-credentials

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo "$(echo $DOCKER_HUB_CREDENTIALS | jq -r '.username'):$DOCKER_HUB_PASSWORD" | docker login --username $(echo $DOCKER_HUB_CREDENTIALS | jq -r '.username') --password-stdin
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $ECR_REPO_URI:latest .
      - docker tag $ECR_REPO_URI:latest $ECR_REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing the Docker images..."
      - docker push $ECR_REPO_URI:latest || { echo 'Docker push latest failed'; exit 1; }
      - docker push $ECR_REPO_URI:$IMAGE_TAG || { echo "Docker push $IMAGE_TAG failed"; exit 1; }

artifacts:
  files:
    - '**/*'

image:
  name: aws/codebuild/standard:5.0
  computeType: BUILD_GENERAL1_SMALL
