version: 0.2

env:
  variables:
    ECR_REPO_URI: "033914078355.dkr.ecr.us-east-1.amazonaws.com/example-repo"
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $ECR_REPO_URI:$IMAGE_TAG .
      - docker tag $ECR_REPO_URI:$IMAGE_TAG $ECR_REPO_URI:latest
      - docker images

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $ECR_REPO_URI:$IMAGE_TAG || { echo "Docker push $IMAGE_TAG failed"; exit 1; }
      - docker push $ECR_REPO_URI:latest || { echo 'Docker push latest failed'; exit 1; }

artifacts:
  files:
    - '**/*'

image:
  name: aws/codebuild/standard:5.0
  computeType: BUILD_GENERAL1_SMALL
